apiVersion: v2
name: addressbook
description: Helm chart for User Address Directory API
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - springboot
  - api
  - addressbook
maintainers:
  - name: DevOps Team
    email: devops@example.com
